import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin-ext"],
})

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin-ext"],
})

export const metadata: Metadata = {
  title: "TUM Blockchain Club",
  description: "Generated by create next app",
  keywords: ["TUM", "Blockchain"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
