import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import { Header } from "@/components/header";

import "./globals.css";
import { MenuLink } from "@/components/header/Header";
import { Footer } from "@/components/footer";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin-ext"],
})

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin-ext"],
})

export const metadata: Metadata = {
  title: "TUM Blockchain Club",
  description: "Generated by create next app",
  keywords: ["TUM", "Blockchain"],
};

const menuLinks : MenuLink[] = [
  {
    name: "About",
    url: "/about",
    buttonType: "link"
  },
  {
    name: "Events",
    url: "/about",
    buttonType: "link"
  },
  {
    name: "Industry",
    url: "/about",
    buttonType: "link"
  },
  {
    name: "Conference",
    url: "/about",
    buttonType: "link"
  },
  {
    name: "Join Us",
    url: "/about",
    buttonType: "primary"
  }
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-mode="dark" className={`${manrope.variable} ${inter.variable} antialiased bg-background overflow-x-hidden max-w-screen`}>
      <body>
        <Header menuLinks={menuLinks} logo="/tbc-wordmark.png"/>
          {children}
        <Footer/>
      </body>
    </html>
  );
}
